
# Running : docker build   --build-arg BUILD_ARGUMENT_ENV=dev --file test/dockerfile_sdk_issue .  --no-cache
# Return error code 6

# Running : docker build --target DEBIAN_BUILD  --file test/dockerfile_sdk .  --no-cache
# Return error code 6

ARG BUILD_ARGUMENT_ENV
FROM debian:12-slim as DEBIAN_BUILD




# check environment
RUN if [ "$BUILD_ARGUMENT_ENV" = "default" ]; then echo "Set BUILD_ARGUMENT_ENV in docker build-args like --build-arg BUILD_ARGUMENT_ENV=dev" && exit 3; \
    elif [ "$BUILD_ARGUMENT_ENV" = "dev" ]; then echo "Building development environment."; \
    elif [ "$BUILD_ARGUMENT_ENV" = "test" ]; then echo "Building test environment."; \
    elif [ "$BUILD_ARGUMENT_ENV" = "staging" ]; then echo "Building staging environment."; \
    elif [ "$BUILD_ARGUMENT_ENV" = "prod" ]; then echo "Building production environment."; \
    else echo "Set correct BUILD_ARGUMENT_ENV in docker build-args like --build-arg BUILD_ARGUMENT_ENV=dev. Available choices are dev,test,staging,prod." && exit 6; \
    fi
RUN echo "Using ${BUILD_ARGUMENT_ENV} as build env"

# FROM php:8.2-apache