ARG my_arg=-1

FROM centos:7 AS base
RUN echo "do stuff with the centos image"



# Doesn't work either..;
RUN if [ "$my_arg" = "-1" ]; then echo "Set my_arg in docker " && exit 2; \
    else echo "FULL_PHP_VERSION is set"; \
    fi

# FROM base AS branch-version-1
RUN echo "this is the stage that sets VAR=TRUE"
ENV VAR=TRUE

# FROM base AS branch-version-2
RUN echo "this is the stage that sets VAR=FALSE"
ENV VAR=FALSE

# FROM branch-version-${my_arg} AS final
RUN echo "my_arg is equal to ${my_arg}"