
# Running : docker build --target DEBIAN_BUILD  --build-arg BUILD_ARGUMENT_ENV="dev" --file test/dockerfile_sdk .  --no-cache
# Return error code 6

# Running : docker build --target DEBIAN_BUILD  --file test/dockerfile_sdk .  --no-cache
# Return error code 6

FROM debian:12-slim as DEBIAN_BUILD
ARG BUILD_ARGUMENT_ENV




# check environment
RUN if [ "$BUILD_ARGUMENT_ENV" = "default" ]; then echo "Set BUILD_ARGUMENT_ENV in docker build-args like --build-arg BUILD_ARGUMENT_ENV=dev" && exit 3; \
    elif [ "$BUILD_ARGUMENT_ENV" = "dev" ]; then echo "Building development environment."; \
    elif [ "$BUILD_ARGUMENT_ENV" = "test" ]; then echo "Building test environment."; \
    elif [ "$BUILD_ARGUMENT_ENV" = "staging" ]; then echo "Building staging environment."; \
    elif [ "$BUILD_ARGUMENT_ENV" = "prod" ]; then echo "Building production environment."; \
    else echo "Set correct BUILD_ARGUMENT_ENV in docker build-args like --build-arg BUILD_ARGUMENT_ENV=dev. Available choices are dev,test,staging,prod." && exit 6; \
    fi

# FROM php:8.2-apache